language: python
python:
  - "2.7"
  - "3.8"
  # command to install dependencies
install: "pip install -r requirement.txt"
# command to run tests
script: coverage run TestCheckSeason.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>="
  secret_access_key:
    secure: "Encypted <secret-access-key>="
  region: "us-east-1"
  app: "example-app-name"
  env: "example-app-environment"
  bucket_name: "the-target-S3-bucket"
