
# language: python
# python:
#  - "2.7"
#  - "3.8"
  # command to install dependencies
# install: "pip install -r requirement.txt"
# command to run tests
# script: coverage run TestCheckSeason.py
# after_success:
#  - bash <(curl -s https://codecov.io/bash)

sudo: required
language: python
services:
- docker


script:
- docker image build -t arshiaryerson/cps847-a2 .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push arshiaryerson/cps847-a2

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET
  region: "us-east-2"
  app: "cps847-a2"
  env: "Cps847-a2-env"
  bucket_name: "elasticbeanstalk-us-east-2-517095703763"
  on:
    branch: "main"
