sudo: required
language: python
services:
- docker


script:
- docker image build -t cps847a2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push cps847a2

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: ""
  secret_access_key:
    secure: ""
  region: "us-east-1"
  app: "cps847-a2"
  env: "cps847-a2-env"
  bucket_name: "the-target-S3-bucket"
