language: python
python:
  - "2.7"
  - "3.8"
  # command to install dependencies
install: "pip install -r requirement.txt"
# command to run tests
script: coverage run TestCheckSeason.py
after_success:
  - bash <(curl -s https://codecov.io/bash)

